// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: Income.proto

package expense

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Income struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Date   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Income) Reset() {
	*x = Income{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Income) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Income) ProtoMessage() {}

func (x *Income) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Income.ProtoReflect.Descriptor instead.
func (*Income) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{0}
}

func (x *Income) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Income) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Income) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type CreateIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Date   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *CreateIncomeRequest) Reset() {
	*x = CreateIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncomeRequest) ProtoMessage() {}

func (x *CreateIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncomeRequest.ProtoReflect.Descriptor instead.
func (*CreateIncomeRequest) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIncomeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateIncomeRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type CreateIncomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncomeId string `protobuf:"bytes,1,opt,name=income_id,json=incomeId,proto3" json:"income_id,omitempty"`
}

func (x *CreateIncomeResponse) Reset() {
	*x = CreateIncomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIncomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncomeResponse) ProtoMessage() {}

func (x *CreateIncomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncomeResponse.ProtoReflect.Descriptor instead.
func (*CreateIncomeResponse) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIncomeResponse) GetIncomeId() string {
	if x != nil {
		return x.IncomeId
	}
	return ""
}

type GetIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncomeId string `protobuf:"bytes,1,opt,name=income_id,json=incomeId,proto3" json:"income_id,omitempty"`
}

func (x *GetIncomeRequest) Reset() {
	*x = GetIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomeRequest) ProtoMessage() {}

func (x *GetIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomeRequest.ProtoReflect.Descriptor instead.
func (*GetIncomeRequest) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{3}
}

func (x *GetIncomeRequest) GetIncomeId() string {
	if x != nil {
		return x.IncomeId
	}
	return ""
}

type GetIncomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Income *Income `protobuf:"bytes,1,opt,name=income,proto3" json:"income,omitempty"`
}

func (x *GetIncomeResponse) Reset() {
	*x = GetIncomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomeResponse) ProtoMessage() {}

func (x *GetIncomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomeResponse.ProtoReflect.Descriptor instead.
func (*GetIncomeResponse) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{4}
}

func (x *GetIncomeResponse) GetIncome() *Income {
	if x != nil {
		return x.Income
	}
	return nil
}

type UpdateIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncomeId string                 `protobuf:"bytes,1,opt,name=income_id,json=incomeId,proto3" json:"income_id,omitempty"`
	Amount   float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Date     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *UpdateIncomeRequest) Reset() {
	*x = UpdateIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncomeRequest) ProtoMessage() {}

func (x *UpdateIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncomeRequest.ProtoReflect.Descriptor instead.
func (*UpdateIncomeRequest) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIncomeRequest) GetIncomeId() string {
	if x != nil {
		return x.IncomeId
	}
	return ""
}

func (x *UpdateIncomeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateIncomeRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type UpdateIncomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncomeId string `protobuf:"bytes,1,opt,name=income_id,json=incomeId,proto3" json:"income_id,omitempty"`
}

func (x *UpdateIncomeResponse) Reset() {
	*x = UpdateIncomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIncomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncomeResponse) ProtoMessage() {}

func (x *UpdateIncomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncomeResponse.ProtoReflect.Descriptor instead.
func (*UpdateIncomeResponse) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateIncomeResponse) GetIncomeId() string {
	if x != nil {
		return x.IncomeId
	}
	return ""
}

type DeleteIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncomeId string `protobuf:"bytes,1,opt,name=income_id,json=incomeId,proto3" json:"income_id,omitempty"`
}

func (x *DeleteIncomeRequest) Reset() {
	*x = DeleteIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIncomeRequest) ProtoMessage() {}

func (x *DeleteIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIncomeRequest.ProtoReflect.Descriptor instead.
func (*DeleteIncomeRequest) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIncomeRequest) GetIncomeId() string {
	if x != nil {
		return x.IncomeId
	}
	return ""
}

type DeleteIncomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteIncomeResponse) Reset() {
	*x = DeleteIncomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Income_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIncomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIncomeResponse) ProtoMessage() {}

func (x *DeleteIncomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Income_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIncomeResponse.ProtoReflect.Descriptor instead.
func (*DeleteIncomeResponse) Descriptor() ([]byte, []int) {
	return file_Income_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteIncomeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_Income_proto protoreflect.FileDescriptor

var file_Income_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x06, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x5d, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x2f,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x22,
	0x3c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x2e, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x22, 0x7a, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x32,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4d, 0x69, 0x6b, 0x65, 0x4d, 0x77, 0x69, 0x74, 0x61, 0x2f, 0x66, 0x65, 0x64,
	0x68, 0x61, 0x2d, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Income_proto_rawDescOnce sync.Once
	file_Income_proto_rawDescData = file_Income_proto_rawDesc
)

func file_Income_proto_rawDescGZIP() []byte {
	file_Income_proto_rawDescOnce.Do(func() {
		file_Income_proto_rawDescData = protoimpl.X.CompressGZIP(file_Income_proto_rawDescData)
	})
	return file_Income_proto_rawDescData
}

var file_Income_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_Income_proto_goTypes = []interface{}{
	(*Income)(nil),                // 0: expense.Income
	(*CreateIncomeRequest)(nil),   // 1: expense.CreateIncomeRequest
	(*CreateIncomeResponse)(nil),  // 2: expense.CreateIncomeResponse
	(*GetIncomeRequest)(nil),      // 3: expense.GetIncomeRequest
	(*GetIncomeResponse)(nil),     // 4: expense.GetIncomeResponse
	(*UpdateIncomeRequest)(nil),   // 5: expense.UpdateIncomeRequest
	(*UpdateIncomeResponse)(nil),  // 6: expense.UpdateIncomeResponse
	(*DeleteIncomeRequest)(nil),   // 7: expense.DeleteIncomeRequest
	(*DeleteIncomeResponse)(nil),  // 8: expense.DeleteIncomeResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_Income_proto_depIdxs = []int32{
	9, // 0: expense.Income.date:type_name -> google.protobuf.Timestamp
	9, // 1: expense.CreateIncomeRequest.date:type_name -> google.protobuf.Timestamp
	0, // 2: expense.GetIncomeResponse.income:type_name -> expense.Income
	9, // 3: expense.UpdateIncomeRequest.date:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Income_proto_init() }
func file_Income_proto_init() {
	if File_Income_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Income_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Income); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIncomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIncomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIncomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Income_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIncomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Income_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Income_proto_goTypes,
		DependencyIndexes: file_Income_proto_depIdxs,
		MessageInfos:      file_Income_proto_msgTypes,
	}.Build()
	File_Income_proto = out.File
	file_Income_proto_rawDesc = nil
	file_Income_proto_goTypes = nil
	file_Income_proto_depIdxs = nil
}
